### ISSUE TITLE
How to add plugins to Image IO

### ISSUE THREAD

**Issue by imanga** [tmyroadctfig/jcgm#1]

**Comment by tmyroadctfig** [comment]
In the project I'm using it for, we just call paint directly on the CGM classes. So we're not registering with ImageIO. I don't think the library has any Image IO SPI classes at present.

This is how we're calling it:
```
            Graphics2D g;
            CGMDisplay display = new CGMDisplay(cgm);
            display.scale(g, (int) cgm.getSize(dpi).getWidth(), (int) cgm.getSize(dpi).getHeight());
            display.paint(g);
```

**Comment by imanga** [comment]
Then is it possible to convert CGM file to SVG

**Comment by tmyroadctfig** [comment]
Looking at the docs they claim that it is integrated with ImageIO: https://github.com/tmyroadctfig/jcgm/blob/master/core/trunk/src/documentation/content/xdocs/howto.xml#L66  ...But I can't see and ImageReader implementations in there. 

You might need to do a bit of research, as I mentioned I'm only using it to paint to a Graphics object. The original source forge page may have some additional info.

**Comment by imanga** [comment]
> _No description provided._
